version: '3'

services:
  hnf-api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    command: ["npm", "run", "dev"]
    container_name: "hnf-api"
    depends_on:
      - mongodbb
    env_file:
      - ./.env
    ports:
      - "3030:3030"
    restart: unless-stopped
    volumes:
      - api_node_modules:/app/node_modules
      - .:/app

  mongodbb:
    image: mongo
    container_name: "mongodbb"
    env_file:
      - ./.env
    ports:
      - "27017-27019:27017-27019"
    logging:
      driver: 'none'
    restart: unless-stopped
    volumes:
      - data-mongodbb:/data/db
    command: --quiet

volumes:
  data-mongodbb:
  api_node_modules:
